token: '123456:ABC-DEF1234ghIkl-zyx57W2v1u123ew11'
chatId: '0000000000000'
# sending notifications as new message
notifications:
  playerJoin: false
  playerQuit: false
  sendSilently: false
  prefix:
    enabled: false
    text: "[Minecraft] "
# adds or removes players from an existing pinned message
# `Group Admin Rights>Pin Messages` must be enabled in bot settings for auto-pin or pin manually
playersList:
  enabled: false
  #message id must be a number (do not change manually or change it to 0 for a new message)
  messageId: 0
  header:
    enabled: false
    # markdown supported (parseMode = "Markdown")
    text: |
      IP: `127.0.0.1:25565`
      Website: [https://example.org](https://example.org)
  footer:
    enabled: false
    # markdown supported (parseMode = "Markdown")
    text: |
      Author: [Example](https://link.to/personal-page)