token: "123456:ABC-DEF1234ghIkl-zyx57W2v1u123ew11"
chatId: "0000000000000"
# sending notifications as new message
notifications:
  playerJoin: false
  playerQuit: false
  prefix:
    enabled: false
    text: "[Minecraft] "
# adds or removes players from an existing pinned message
playersList:
  enabled: false
  #message id must be a number
  messageId: 0
  header:
    enabled: false
    # markdown supported
    text: |
      IP: 127.0.0.1:25565
      Website: [https://example.org](https://example.org)
  footer:
    enabled: false
    # markdown supported
    text: |
      Author: [Example](https://link.to/personal-page)