token: 'TOKEN_HERE'
chatId: 'CHAT_ID_HERE'
# sending notifications as new message
notifications:
  enabled: false
  prefix:
    enabled: false
    text: '[Minecraft] '
#adds or removes players from an existing pinned message
playersList:
  enabled: false
  messageId: 'MESSAGE_ID_HERE'
  additionalInfo: |
    here is your additional information that should be in the message
    for example server ip address or project website