name: TelegramNotifier
version: '${version}'
main: io.github.eone666.telegramnotifier.TelegramNotifier
api-version: "1.20"
libraries:
  - "org.jetbrains.kotlin:kotlin-stdlib:1.8.10"
  - "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.7.3"
  - "com.github.shynixn.mccoroutine:mccoroutine-bukkit-api:2.13.0"
  - "com.github.shynixn.mccoroutine:mccoroutine-bukkit-core:2.13.0"
permissions:
  "telegramnotifier.setup":
    description: "Telegram Notifier /setup command"
    default: op
  "telegramnotifier.config":
    description: "Telegram Notifier configuration commands"
    default: op
  "telegramnotifier.*":
    description: "All Telegram Notifier Commands"
    default: op
    children:
      "telegramnotifier.setup": true
      "telegramnotifier.config": true
commands:
  setup:
    description: "Setup Telegram Notifier"
    usage: "Usage: /setup <token>"
    permission: "telegramnotifier.setup"
  cancelsetup:
    description: "Cancel Telegram Notifier setup"
    usage: "Usage: /cancelsetup"
    permission: "telegramnotifier.setup"
  config:
    description: "Configure Telegram Notifier"
    usage: "Usage: /config <key> <value>"
    permission: "telegramnotifier.config"